name: Security Scan

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]
    schedule:
        - cron: '00 11 * * 2'

jobs:
  securityscan:
    name: Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: TruffleHog Secrets Scanner
        uses: trufflesecurity/trufflehog@v3.47.0
        with:
          path: ./
          base: ${{ github.event.repository.default_branch }}
          head: HEAD
          extra_args: --debug --only-verified
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
            languages: python
      - name: Autobuild
        uses: github/codeql-action/autobuild@v2
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
